import '@/globals.css';
import type { Metadata } from 'next';
import HeaderNav from '@/components/HeaderNav';
import { AuthProvider } from '@/components/context/AuthContext';
import { ToastContainer, Zoom } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='bg-slate-200'>
        <AuthProvider>
        <HeaderNav />
        <ToastContainer 
          position='bottom-left'
          hideProgressBar={true}
          closeOnClick={true}
          autoClose={false}
          theme='colored'
          transition={Zoom}
          limit={1}
        />
        <main>
          {children}
        </main>
        </AuthProvider>
      </body>
    </html>
  );
}
