import '@/globals.css';
import type { Metadata } from 'next';
import HeaderNav from '@/components/HeaderNav';
import { AuthProvider } from '@/components/context/AuthContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='bg-slate-200'>
        <AuthProvider>
        <HeaderNav />
        <main >
          {children}
        </main>
        </AuthProvider>
      </body>
    </html>
  );
}
